[package]
authors = ["Gio d'Amelio <giodamelio@gmail.com>"]
name = "git-shell-info"
version = "0.1.0"

[dependencies]
clap = "2.13.0"
git2 = "0.4.4"
mustache = "0.7.0"
quick-error = "1.1.0"
rustc-serialize = "0.3.19"
